name: CI

on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable

      - name: Run test
        run: cargo test

  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable

      - name: Generate documentation
        run: cargo doc --no-deps --document-private-items --all-features

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable --component rustfmt
          rustup override set stable

      - name: Check code format
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable --component clippy
          rustup override set stable

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test, docs, format, lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable

      - name: Publish package
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
